#!/usr/bin/env sh

cd ~
export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=16
export XFONT_SIZE=16
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus

# qt applications
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM="wayland"
export QT_QPA_PLATFORMTHEME=qt5ct

# env variables for gtk
#gsettings set org.gnome.desktop.interface icon-theme 'Win11-dark'
#gsettings set org.gnome.desktop.interface gtk-theme 'Gruvbox-Dark-BL'
#gsettings set org.gnome.desktop.interface cursor-theme 'WhiteSur Cursors'
#gsettings set org.gnome.desktop.interface font-name 'JetBrainsMono Nerd Font'

export WLR_NO_HARDWARE_CURSORS=1
export WLR_RENDERER_ALLOW_SOFTWARE=1
exec Hyprland
